### ISSUE TITLE
fault: DLL(reason: "dlopen(/usr/local/lib/libtensorflow.so, 2): image not found")

### ISSUE THREAD

**Issue by lunnersword** [PerfectlySoft/Perfect-TensorFlow#6]
# Issues
git clone https://github.com/PerfectExamples/Perfect-TensorFlow-Demo-Vision.git
cd Perfect-TensorFlow-Demo-Vision
./install.sh
./.build/debug/PerfectTensorFlowDemo

I get error as below:
fault: DLL(reason: "dlopen(/usr/local/lib/libtensorflow.so, 2): image not found")

**Comment by RockfordWei** [comment]
@lunnersword Thanks for the issue report. It should be fixed now, if you are using macOS with Swift 5.2. Please re-run the `./install.sh`, then just `swift run`
